> Task :compileJava UP-TO-DATE
> Task :processResources
> Task :classes
> Task :resolveMainClassName

> Task :bootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.5.4)

2025-09-20T18:01:46.631+03:00  INFO 44204 --- [fantasy] [           main] com.example.fantasy.FantasyApplication   : Starting FantasyApplication using Java 17.0.14 with PID 44204 (/Users/Apple/Downloads/fantasy/build/classes/java/main started by Apple in /Users/Apple/Downloads/fantasy)
2025-09-20T18:01:46.633+03:00  INFO 44204 --- [fantasy] [           main] com.example.fantasy.FantasyApplication   : No active profile set, falling back to 1 default profile: "default"
2025-09-20T18:01:47.083+03:00  INFO 44204 --- [fantasy] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2025-09-20T18:01:47.135+03:00  INFO 44204 --- [fantasy] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 47 ms. Found 17 JPA repository interfaces.
2025-09-20T18:01:47.420+03:00  INFO 44204 --- [fantasy] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2025-09-20T18:01:47.431+03:00  INFO 44204 --- [fantasy] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-09-20T18:01:47.431+03:00  INFO 44204 --- [fantasy] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.43]
2025-09-20T18:01:47.468+03:00  INFO 44204 --- [fantasy] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-09-20T18:01:47.469+03:00  INFO 44204 --- [fantasy] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 814 ms
2025-09-20T18:01:47.563+03:00  INFO 44204 --- [fantasy] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-09-20T18:01:47.682+03:00  INFO 44204 --- [fantasy] [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3a11c0eb
2025-09-20T18:01:47.682+03:00  INFO 44204 --- [fantasy] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-09-20T18:01:52.757+03:00  INFO 44204 --- [fantasy] [           main] liquibase.database                       : Set default schema name to public
2025-09-20T18:01:52.951+03:00  INFO 44204 --- [fantasy] [           main] liquibase.changelog                      : Reading from public.databasechangelog
2025-09-20T18:01:53.068+03:00  INFO 44204 --- [fantasy] [           main] liquibase.lockservice                    : Successfully acquired change log lock
2025-09-20T18:01:53.069+03:00  INFO 44204 --- [fantasy] [           main] liquibase.command                        : Using deploymentId: 8380507550
2025-09-20T18:01:53.070+03:00  INFO 44204 --- [fantasy] [           main] liquibase.changelog                      : Reading from public.databasechangelog
2025-09-20T18:01:53.073+03:00  INFO 44204 --- [fantasy] [           main] liquibase.ui                             : Running Changeset: db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie
2025-09-20T18:01:53.096+03:00 ERROR 44204 --- [fantasy] [           main] liquibase.changelog                      : ChangeSet db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie encountered an exception.

liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:497) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:185) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1189) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:790) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:126) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:70) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeLogIterator.lambda$run$0(ChangeLogIterator.java:133) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeLogIterator.lambda$run$1(ChangeLogIterator.java:122) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:267) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:271) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:91) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:114) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:112) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:100) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:253) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.CommandScope.execute(CommandScope.java:241) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:216) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:1333) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:205) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:188) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:326) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:278) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:271) ~[liquibase-core-4.31.1.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1873) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1822) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:607) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:970) ~[spring-context-6.2.9.jar:6.2.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) ~[spring-context-6.2.9.jar:6.2.9]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1361) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350) ~[spring-boot-3.5.4.jar:3.5.4]
	at com.example.fantasy.FantasyApplication.main(FantasyApplication.java:11) ~[main/:na]
Caused by: org.postgresql.util.PSQLException: ERROR: relation "users" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2734) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2421) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:357) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:342) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:318) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:313) ~[postgresql-42.7.7.jar:42.7.7]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-6.3.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-6.3.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:491) ~[liquibase-core-4.31.1.jar:na]
	... 65 common frames omitted

2025-09-20T18:01:53.101+03:00  INFO 44204 --- [fantasy] [           main] liquibase.util                           : UPDATE SUMMARY
2025-09-20T18:01:53.101+03:00  INFO 44204 --- [fantasy] [           main] liquibase.util                           : Run:                          0
2025-09-20T18:01:53.101+03:00  INFO 44204 --- [fantasy] [           main] liquibase.util                           : Previously run:               4
2025-09-20T18:01:53.101+03:00  INFO 44204 --- [fantasy] [           main] liquibase.util                           : Filtered out:                 0
2025-09-20T18:01:53.101+03:00  INFO 44204 --- [fantasy] [           main] liquibase.util                           : -------------------------------
2025-09-20T18:01:53.101+03:00  INFO 44204 --- [fantasy] [           main] liquibase.util                           : Total change sets:            5
2025-09-20T18:01:53.101+03:00  INFO 44204 --- [fantasy] [           main] liquibase.util                           : Update summary generated
2025-09-20T18:01:53.102+03:00  INFO 44204 --- [fantasy] [           main] liquibase.command                        : Update command encountered an exception.
2025-09-20T18:01:53.104+03:00  INFO 44204 --- [fantasy] [           main] liquibase.lockservice                    : Successfully released change log lock
2025-09-20T18:01:53.105+03:00  INFO 44204 --- [fantasy] [           main] liquibase.command                        : Logging exception.
2025-09-20T18:01:53.105+03:00  INFO 44204 --- [fantasy] [           main] liquibase.ui                             : ERROR: Exception Details
2025-09-20T18:01:53.105+03:00  INFO 44204 --- [fantasy] [           main] liquibase.ui                             : ERROR: Exception Primary Class:  PSQLException
2025-09-20T18:01:53.105+03:00  INFO 44204 --- [fantasy] [           main] liquibase.ui                             : ERROR: Exception Primary Reason:  ERROR: relation "users" already exists
2025-09-20T18:01:53.105+03:00  INFO 44204 --- [fantasy] [           main] liquibase.ui                             : ERROR: Exception Primary Source:  PostgreSQL 17.6
2025-09-20T18:01:53.105+03:00  INFO 44204 --- [fantasy] [           main] liquibase.command                        : Command execution complete
2025-09-20T18:01:54.611+03:00  WARN 44204 --- [fantasy] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Failed to initialize dependency 'liquibase' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
2025-09-20T18:01:54.612+03:00  INFO 44204 --- [fantasy] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-09-20T18:01:54.614+03:00  INFO 44204 --- [fantasy] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-09-20T18:01:54.618+03:00  INFO 44204 --- [fantasy] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2025-09-20T18:01:54.633+03:00  INFO 44204 --- [fantasy] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2025-09-20T18:01:54.645+03:00 ERROR 44204 --- [fantasy] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Failed to initialize dependency 'liquibase' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:328) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:970) ~[spring-context-6.2.9.jar:6.2.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) ~[spring-context-6.2.9.jar:6.2.9]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1361) ~[spring-boot-3.5.4.jar:3.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350) ~[spring-boot-3.5.4.jar:3.5.4]
	at com.example.fantasy.FantasyApplication.main(FantasyApplication.java:11) ~[main/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1826) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:607) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:339) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:373) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-6.2.9.jar:6.2.9]
	... 10 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:288) ~[liquibase-core-4.31.1.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1873) ~[spring-beans-6.2.9.jar:6.2.9]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1822) ~[spring-beans-6.2.9.jar:6.2.9]
	... 17 common frames omitted
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:300) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.CommandScope.execute(CommandScope.java:241) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:216) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:1333) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:205) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:188) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:326) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.lambda$afterPropertiesSet$0(SpringLiquibase.java:278) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:271) ~[liquibase-core-4.31.1.jar:na]
	... 19 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:155) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:114) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:112) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:100) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:253) ~[liquibase-core-4.31.1.jar:na]
	... 37 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/changes/0001-initial-schema.yaml::0001-initial::junie:
     Reason: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:840) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:126) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:70) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeLogIterator.lambda$run$0(ChangeLogIterator.java:133) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeLogIterator.lambda$run$1(ChangeLogIterator.java:122) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:201) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:210) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:200) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:267) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.Scope.child(Scope.java:271) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:91) ~[liquibase-core-4.31.1.jar:na]
	... 45 common frames omitted
Caused by: liquibase.exception.DatabaseException: ERROR: relation "users" already exists [Failed SQL: (0) CREATE TABLE public.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(120) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE, CONSTRAINT users_pkey PRIMARY KEY (id), UNIQUE (username), UNIQUE (email))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:497) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:185) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1189) ~[liquibase-core-4.31.1.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:790) ~[liquibase-core-4.31.1.jar:na]
	... 60 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: relation "users" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2734) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2421) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:518) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:357) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:342) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:318) ~[postgresql-42.7.7.jar:42.7.7]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:313) ~[postgresql-42.7.7.jar:42.7.7]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-6.3.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-6.3.1.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:491) ~[liquibase-core-4.31.1.jar:na]
	... 65 common frames omitted


> Task :bootRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/Users/Apple/Library/Java/JavaVirtualMachines/jbr-17.0.14/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 9s
4 actionable tasks: 3 executed, 1 up-to-date
Exception in thread "Thread-0" org.gradle.api.UncheckedIOException: java.io.IOException: Input/output error
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:42)
	at org.gradle.internal.daemon.client.clientinput.DaemonClientInputForwarder$ForwardingUserInput.lambda$readAndForwardStdin$0(DaemonClientInputForwarder.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Input/output error
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:287)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:345)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:350)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:393)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
